[package]
name = "cch23-uptonm"
version = "0.1.0"
edition = "2021"

[dependencies]
indoc = "2.0.4"
itertools = "0.12.0"
rocket = { version = "0.5.0", features = ["json"] }
shuttle-rocket = "0.34.0"
shuttle-runtime = "0.34.0"
tokio = "1.26.0"
